// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLaTW98QU9bnD1-t_VNoE4qFPeoEzDE5g',
    appId: '1:159020518470:web:28a69f85f62cdccb0fce47',
    messagingSenderId: '159020518470',
    projectId: 'tregaxmuse',
    authDomain: 'tregaxmuse.firebaseapp.com',
    storageBucket: 'tregaxmuse.firebasestorage.app',
    measurementId: 'G-ZBW5N9Y7QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQbhshdJB4LAjdLtb4i-qdyuybZkDmAjk',
    appId: '1:159020518470:android:5c1b6242d93b03100fce47',
    messagingSenderId: '159020518470',
    projectId: 'tregaxmuse',
    storageBucket: 'tregaxmuse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbO5tGPwRnmWTXXy9tQ-4E5aUOyuLKnOw',
    appId: '1:159020518470:ios:66d83d5c37b454e10fce47',
    messagingSenderId: '159020518470',
    projectId: 'tregaxmuse',
    storageBucket: 'tregaxmuse.firebasestorage.app',
    iosBundleId: 'com.trega.trega',
  );
}
